spring.application.name=core-logic-service
server.port=8080

# PostgreSQL Connection Pipeline
spring.datasource.url=jdbc:postgresql://localhost:5432/core_db
spring.datasource.username=admin
spring.datasource.password=securepassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ Event Broker Configurations
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest